In [1]:
import numpy as np
x = [3, 2, 4, 5, 1]
y = np.array(x)
y

array([3, 2, 4, 5, 1])

In [2]:
np.sort(y)

array([1, 2, 3, 4, 5])

In [3]:
x.sort()    # Karena bentuk list, maka bisa di sort menggunakan ini
x

[1, 2, 3, 4, 5]

In [4]:
np.sort(y)[::-1]       # Sortir descending dengan Numpy

array([5, 4, 3, 2, 1])

In [5]:
x.sort(reverse=True)   # Sortir descending dengan List
x

[5, 4, 3, 2, 1]

In [6]:
# Membuat fungsi sort ascending
def ascen(param):
    newDraft = list(param)
    for i in range(len(newDraft)):
        for j in range(i+1, len(newDraft)):
            if newDraft[i] > newDraft[j]:
                newDraft[i], newDraft[j] = newDraft[j], newDraft[i]
    return newDraft
ascen(x)

[1, 2, 3, 4, 5]

In [7]:
# Membuat fungsi sort descending
def descen(input):
    newDraft = list(input)
    for i in range(len(newDraft)):
        for j in range(i+1, len(newDraft)):
            if newDraft[i] < newDraft[j]:
                newDraft[i], newDraft[j] = newDraft[j], newDraft[i]
    return newDraft
descen(x)

[5, 4, 3, 2, 1]

In [8]:
# Alternatif sort ascending
isi    = [3, 32, 89, 1, 120]
sortir = []
i = 0
minX   = isi[0]
while len(isi) > 0:
    if isi[i] <= minX:
        minX = isi[i]
    i += 1
    if i == len(isi):
        sortir.append(minX)
        isi.remove(minX)
        if isi:
            minX= isi[0]
        i = 0

print(sortir)

[1, 3, 32, 89, 120]


In [9]:
import numpy as np
z = [[9, 10, 2], [5, 1, 4]]
z = np.array(z)
np.sort(z)                    # sortir by row

array([[ 2,  9, 10],
       [ 1,  4,  5]])

In [10]:
import numpy as np
y = [[9, 1, 8], [5, 2, 10]]
y = np.array(y)
np.sort(y, axis=0)            # Sort() by col - axis = 0

array([[ 5,  1,  8],
       [ 9,  2, 10]])

In [11]:
np.sort(y, axis=1)            # Sort() by row - axis = 1

array([[ 1,  8,  9],
       [ 2,  5, 10]])